name: Do Something That Needs Scheduled
on:
  workflow_dispatch:
  repository_dispatch:
    types: test
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        run: echo Doing Something...
